In [18]:
import numpy as np
from numpy.linalg import inv

### No.1 Membuat tensor

In [ ]:
tensor_1=np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]],
                   [[9,10],[11,12]],
                   [[5,6],[7,8]]
                   ])
print(tensor_1)

### No.2

In [15]:
a=np.array([[23,50,19],
            [7,12,109],
            [57,67,98],
            ])
print(a)
b=np.array([[17],
            [22],
            [19]])
print(b)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[[17]
 [22]
 [19]]


In [14]:
# Perkalian antara a dan b
# element-wise
wise= a*b
print(wise)
# dot product
dot= a.dot(b)
print(dot)

[[ 391  850  323]
 [ 154  264 2398]
 [1083 1273 1862]]
[[1852]
 [2454]
 [4305]]


### No.3

In [20]:
# menentukan nilai determinan, transpose dan inverse matriks a
# Transpose
print(a.T)
# Determinan
print(np.linalg.det(a))
# inverse
print(np.linalg.inv(a))

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]
131344.0000000002
[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
